
//! Autogenerated weights for `pallet_module_payments`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 50.0.0
//! DATE: 2025-09-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `z90`, CPU: `12th Gen Intel(R) Core(TM) i5-12600KF`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/modnet-runtime/modnet_runtime.wasm
// --pallet
// pallet_module-payments
// --extrinsic
// 
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/module-payments/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_module_payments`.
pub trait WeightInfo {
	fn set_authorized_module() -> Weight;
}

/// Weights for `pallet_module_payments` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Modules::Modules` (r:1 w:0)
	/// Proof: `Modules::Modules` (`max_values`: None, `max_size`: Some(359), added: 2834, mode: `MaxEncodedLen`)
	/// Storage: `ModulePayments::AuthorizedModule` (r:1 w:1)
	/// Proof: `ModulePayments::AuthorizedModule` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set_authorized_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `74`
		//  Estimated: `3824`
		// Minimum execution time: 9_007_000 picoseconds.
		Weight::from_parts(9_481_000, 3824)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Modules::Modules` (r:1 w:0)
	/// Proof: `Modules::Modules` (`max_values`: None, `max_size`: Some(359), added: 2834, mode: `MaxEncodedLen`)
	/// Storage: `ModulePayments::AuthorizedModule` (r:1 w:1)
	/// Proof: `ModulePayments::AuthorizedModule` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	fn set_authorized_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `74`
		//  Estimated: `3824`
		// Minimum execution time: 9_007_000 picoseconds.
		Weight::from_parts(9_481_000, 3824)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
