name: Deploy (Self-Hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Docker is available
        run: |
          docker version
          docker compose version || docker --help

      - name: Build and deploy with Compose
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Build local image and (re)create service
          docker compose up -d --build

      - name: Show running containers
        run: |
          docker ps --format 'table {{.Names}}	{{.Image}}	{{.Status}}	{{.Ports}}'