name: Nix

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: [self-hosted, linux, x64, modnet-runner]
    container:
      image: nixos/nix:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: setup-workspace
        run: |
          rm -rf /_work
          mkdir -p /_work
          mkdir -p /_work/_temp
          mkdir -p /_work/_actions
          mkdir -p /_work/_tool
          mkdir -p /_work/_work

          chmod 777 /_work/_temp 2>/dev/null || true
          chmod 777 /_work/_actions 2>/dev/null || true
          chmod 777 /_work/_tool 2>/dev/null || true
          chmod 777 /_work/_work 2>/dev/null || true
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: true
      - name: Install dependencies
        run: |
          # Install git and cacert
          nix-env -iA nixpkgs.git nixpkgs.cacert
          git config --global --add safe.directory "${{ github.workspace }}"
          
          # Install Node.js for GitHub Actions
          nix-env -iA nixpkgs.nodejs
          mkdir -p /__e/node20/bin
          ln -sf $(which node) /__e/node20/bin/node

      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Nix flake show
        run: nix flake show

      - name: Build in devshell (sanity)
        run: |
          nix develop -c bash -lc "rustup show || true; cargo --version || true; cargo build -q"
